services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend-estatico:latest
    container_name: frontend-estatico
    restart: always
    ports:
      - "80:80"
    environment:
      BACKEND_HOST: ${BACKEND_HOST}
